apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: plasterprojects.plaster.pipelines.openshift.io
spec:
  group: plaster.pipelines.openshift.io
  names:
    kind: PlasterProject
    listKind: PlasterProjectList
    plural: plasterprojects
    singular: plasterproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PlasterProject is the Schema for the plasterprojects API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PlasterProjectSpec defines the desired state of PlasterProject
          properties:
            build:
              description: Build contains the specifications on how to build your
                Plaster project.
              properties:
                dockerfile:
                  description: Dockerfile builds use a provided Dockerfile to build
                    an application
                  properties:
                    dockerfile:
                      description: Dockerfile is the docker file to use. If empty,
                        Plaster assumes you want to build with a `Dockerfile` in the
                        context root.
                      type: string
                  type: object
                language:
                  description: Language builds use a pre-baked set of languages to
                    build an application
                  properties:
                    name:
                      description: Name is the language framework to use to build
                        your application
                      type: string
                    optimized:
                      description: Optmimized indicates if the deployed application
                        should be optimized for running in production
                      type: boolean
                  required:
                  - name
                  - optimized
                  type: object
                type:
                  description: Type is the type of build to use
                  type: string
              required:
              - type
              type: object
            source:
              description: Source is the source code used to run your Plaster project
                build.
              properties:
                git:
                  description: Git is a source from a Git repostority.
                  properties:
                    httpProxy:
                      description: httpProxy is a proxy used to reach the git repository
                        over http
                      type: string
                    httpsProxy:
                      description: httpsProxy is a proxy used to reach the git repository
                        over https
                      type: string
                    noProxy:
                      description: noProxy is the list of domains for which the proxy
                        should not be used
                      type: string
                    ref:
                      description: ref is the branch/tag/ref to build.
                      type: string
                    uri:
                      description: uri points to the source that will be built. The
                        structure of the source will depend on the type of build to
                        run
                      type: string
                  required:
                  - uri
                  type: object
                type:
                  description: Type is the source type for the Plaster project.
                  type: string
              required:
              - type
              type: object
            tests:
              description: Tests lists the tests to run against your source code.
              items:
                properties:
                  command:
                    description: Command is the command and arguments to run in the
                      test
                    items:
                      type: string
                    type: array
                  name:
                    description: Name is the name of the test
                    type: string
                required:
                - name
                type: object
              type: array
          required:
          - build
          - source
          type: object
        status:
          description: PlasterProjectStatus defines the observed state of PlasterProject
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
