apiVersion: apps/v1
kind: Deployment
metadata:
  name: plaster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: plaster
  template:
    metadata:
      labels:
        name: plaster
    spec:
      serviceAccountName: plaster
      containers:
        - name: plaster
          image: quay.io/adambkaplan/plaster-operator:v0.0.0-1
          command:
          - plaster
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "plaster"
